name: Deploy Terraform

on:
  push:
    branches:
      - master
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
    AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terraform
      run: |
        wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
        unzip terraform_1.3.7_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    # - name: Configure remote state
    #   run: |
    #     terraform init -backend-config="access_key=${secrets.AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${secrets.AWS_SECRET_ACCESS_KEY}" -backend-config="bucket=${secrets.TF_STATE_BUCKET}" -backend-config="region=${secrets.AWS_REGION}" -backend-config="path=tf.tfstate"
      
    - name: Configure remote state
      run: |
        terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}" -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="region=${AWS_REGION}"

    # - name: Terraform Plan
    #   run: |
    #     terraform plan

    # - name: Terraform Apply
    #   run: |
    #     terraform apply -var-file=production.tfvars -auto-approve
