name: Deploy Terraform

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terraform
      run: |
        wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
        unzip terraform_1.3.7_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    - name: Configure remote state
      run: |
        terraform init -backend-config="access_key=${secrets.AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${secrets.AWS_SECRET_ACCESS_KEY}" -backend-config="bucket=${secrets.TF_STATE_BUCKET}" -backend-config="region=${secrets.AWS_REGION}" -backend-config="path=tf.tfstate"
      
    # - name: Configure remote state
    #   run: |
    #     terraform init
    # - name: Terraform Plan
    #   run: |
    #     terraform plan -var-file=production.tfvars

    # - name: Terraform Apply
    #   run: |
    #     terraform apply -var-file=production.tfvars -auto-approve
