name: Destroy Infrastructure with Terraform

on:
  workflow_dispatch:
    
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
    AWS_REGION: ${{ secrets.AWS_REGION }}
    EC2_AMI:   ${{ secrets.EC2_AMI }}
    NAMESPACE: ${{ secrets.NAMESPACE }}
    USER: ${{ secrets.USER }}
jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terraform
      run: |
        wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
        unzip terraform_1.3.7_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
    - name: Init Terraform with remote state
      run: |
        terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}" -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="region=${AWS_REGION}"
    - name: Terraform Destroy
      run: |
        terraform destroy -var 'pa_token=${{ secrets.GIT_TOKEN }}' -var 'namespace=${NAMESPACE}' -var 'repository=${{ secrets.REPOSITORY }}' -var 'user=${USER}' -var 'ec2_ami=ami-04bad3c587fe60d89' -auto-approve
